# 11. Create two arrays a and b and initialize them with random numbers. Stack them vertically. 
# Then, try to create another array, stacking arrays a and b horizontally.(take care of their size).

In [6]:
import numpy as np
import random


In [7]:
np_a = np.random.randint(1,10,size=(5,))
np_b = np.random.randint(1,10,size=(7,))

In [8]:
# getting the differene of size in case arrays aren't the same size
print(np_a, np_a.size, np_a.shape)
print(np_b, np_b.size, np_b.shape)
diff = abs(np_a.size - np_b.size)

[1 7 4 9 4] 5 (5,)
[4 3 2 6 6 3 6] 7 (7,)


In [9]:
# check size
if np_a.size > np_b.size:
	print("np_a.size > np_b.size")
	add_missing = [np.nan for i in range(diff)]
	np_b = np.append(np_b,[add_missing])
if np_a.size < np_b.size:
	print("np_a.size < np_b.size")
	add_missing = [np.nan for i in range(diff)]
	np_a = np.append(np_a,[add_missing])

np_a.size < np_b.size


In [10]:
# stacking
# print(np_a)
np_c = np.stack((np_a, np_b), axis = 1)
print(np_c)


np_c = np.stack((np_a, np_b), axis = 0)
print(np_c)

[[ 1.  4.]
 [ 7.  3.]
 [ 4.  2.]
 [ 9.  6.]
 [ 4.  6.]
 [nan  3.]
 [nan  6.]]
[[ 1.  7.  4.  9.  4. nan nan]
 [ 4.  3.  2.  6.  6.  3.  6.]]
