# 8. Create an array of size 4x4 with random numbers. Transform it into a numpy array.


In [3]:
import numpy as np
import random


In [4]:
# generate 4x4 array w/zeroes
arr = [[0]*4 for i in range(4)]
# arr = [[0 for _ in range(4)] for _ in range(4)]

# fill w/random values 
for i in range(4):
	for j in range(4):
		arr[i][j] = random.randint(1,10)


In [5]:
# convert to numpy array
np_arr = np.array(arr)
print(np_arr, type(np_arr))

[[10  6  3  2]
 [ 4  7  5  4]
 [ 9  4  8  9]
 [ 2  1  6  4]] <class 'numpy.ndarray'>
